# Generated by Django 5.0.6 on 2024-06-21 02:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='height',
            field=models.FloatField(default='1.70'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='weight',
            field=models.FloatField(default='60'),
            preserve_default=False,
        ),
    ]
