# Generated by Django 5.0.6 on 2024-07-11 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StravaToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorize', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_token', models.CharField(null=True)),
                ('refresh_token', models.CharField(null=True)),
                ('expires_at', models.DateTimeField(null=True)),
                ('read', models.BooleanField(default=False)),
                ('read_all', models.BooleanField(default=False)),
                ('profile_read_all', models.BooleanField(default=False)),
                ('activity_read_all', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
