# Generated by Django 5.0.6 on 2024-07-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stravatoken',
            name='authorize',
            field=models.BooleanField(default=False),
        ),
    ]
